export const AGENT_EVENTS: Array<{ text: string; category: string }> = [
  { text: 'User prefers concise, bullet-point responses', category: 'preference' },
  { text: 'User is building a customer support chatbot', category: 'profile' },
  { text: 'User asked how to reduce RAG hallucinations', category: 'query' },
  { text: 'Task completed: summarized 47 support tickets', category: 'agent' },
  { text: 'User prefers Python over TypeScript for AI work', category: 'preference' },
  { text: 'Session started — returning user, 3rd session this week', category: 'system' },
  { text: 'User is a backend engineer at a Series B startup', category: 'profile' },
  { text: 'Agent recalled: user prefers GPT-4o for reasoning tasks', category: 'agent' },
  { text: 'User asked about chunking strategies for long documents', category: 'query' },
  { text: 'Task completed: generated weekly status report', category: 'agent' },
  { text: 'User timezone: PST — schedules meetings before 3pm', category: 'profile' },
  { text: 'Memory conflict detected: user location changed SF → NYC', category: 'agent' },
  { text: 'User asked about hybrid search vs pure vector search', category: 'query' },
  { text: 'Agent observation: user asks follow-up questions 80% of the time', category: 'agent' },
  { text: 'User prefers dark mode across all tools', category: 'preference' },
  { text: 'Task completed: drafted investor update email', category: 'agent' },
  { text: 'New tool integrated: Notion MCP connector deployed', category: 'system' },
  { text: 'User asked about optimal embedding models for code search', category: 'query' },
  { text: 'Agent retrieved 7 relevant memories for current context', category: 'agent' },
  { text: 'User mentioned team uses LangChain for production pipelines', category: 'profile' },
  { text: 'Task completed: extracted action items from meeting transcript', category: 'agent' },
  { text: 'User prefers Claude for writing, GPT-4 for code', category: 'preference' },
  { text: 'Memory pruning: consolidated 12 stale preference entries', category: 'agent' },
  { text: 'User asked about agent memory vs context window tradeoffs', category: 'query' },
  { text: 'Collection backup synced to decentralized storage', category: 'system' },
  { text: 'User is preparing a demo for enterprise customers next week', category: 'profile' },
  { text: 'Agent resolved conflict: user moved team from Jira to Linear', category: 'agent' },
  { text: 'Task completed: classified 200 customer feedback entries', category: 'agent' },
  { text: 'User asked how to implement multi-agent memory sharing', category: 'query' },
  { text: 'API p99 latency: 4.3ms — within SLA', category: 'system' },
  { text: 'User prefers structured JSON output over free-form text', category: 'preference' },
  { text: 'Agent recalled: user is allergic to overly formal language', category: 'agent' },
  { text: 'Task completed: generated personalized onboarding plan', category: 'agent' },
  { text: 'User asked about GraphRAG for multi-hop reasoning', category: 'query' },
  { text: 'Session duration: 22 minutes — engagement above average', category: 'system' },
  { text: 'User mentioned shipping a RAG pipeline to production last week', category: 'profile' },
  { text: 'Merkle root verified — collection integrity confirmed', category: 'system' },
  { text: 'User asked about re-ranking retrieved documents', category: 'query' },
  { text: 'Agent observation: user satisfaction increases with memory context', category: 'agent' },
  { text: 'New preference noted: user reviews PRs on Mondays only', category: 'preference' },
  { text: 'Task completed: created knowledge base from 84 Slack threads', category: 'agent' },
  { text: 'User asked about memory decay strategies for long-running agents', category: 'query' },
  { text: 'Agent retrieved semantically similar memory from 3 sessions ago', category: 'agent' },
  { text: 'User is building a coding assistant for their engineering team', category: 'profile' },
  { text: 'Write proof posted — tamper-evident record created', category: 'system' },
  { text: 'User asked how to handle conflicting memories in long sessions', category: 'query' },
  { text: 'Task completed: weekly memory consolidation — 8 entries merged', category: 'agent' },
  { text: 'User prefers morning standup format for daily summaries', category: 'preference' },
  { text: 'Agent recalled past context — prevented duplicate work', category: 'agent' },
  { text: 'Session ended — 31 memories written, 12 recalled this session', category: 'system' },
];
