export const AGENT_EVENTS: Array<{ text: string; category: string }> = [
  { text: 'User prefers dark mode', category: 'preference' },
  { text: 'User is based in San Francisco', category: 'profile' },
  { text: 'User asked about Solana staking yields', category: 'query' },
  { text: 'Bitcoin hits new ATH at $142,000', category: 'news' },
  { text: 'Fed raises rates by 25bps - markets steady', category: 'news' },
  { text: 'Task completed: summarize Q3 report', category: 'agent' },
  { text: 'Error: rate limit hit on OpenAI API', category: 'system' },
  { text: 'Session started - returning user', category: 'system' },
  { text: 'User authenticated via wallet: 8xjQ…5nP', category: 'system' },
  { text: 'New conversation thread: #thread-2847', category: 'system' },
  { text: 'User interested in DeFi yield farming', category: 'preference' },
  { text: 'Agent recalled: user prefers concise answers', category: 'agent' },
  { text: 'Ethereum gas fees drop below 5 gwei', category: 'news' },
  { text: 'User timezone detected: PST (UTC-8)', category: 'profile' },
  { text: 'Task: compare Pinecone vs VecLabs pricing', category: 'agent' },
  { text: 'User mentioned working at a Series B startup', category: 'profile' },
  { text: 'Solana TPS reaches 65,000 on mainnet', category: 'news' },
  { text: 'Memory conflict: user said SF earlier, now says NYC', category: 'agent' },
  { text: 'Agent observation: user asks follow-up 80% of the time', category: 'agent' },
  { text: 'New integration: LangChain adapter deployed', category: 'system' },
  { text: 'User prefers bullet-point format', category: 'preference' },
  { text: 'Task completed: draft email for investor update', category: 'agent' },
  { text: 'User asked about HNSW algorithm internals', category: 'query' },
  { text: 'Collection backup completed to Shadow Drive', category: 'system' },
  { text: 'Merkle root posted to Solana devnet: tx confirmed', category: 'system' },
  { text: 'User language preference: English', category: 'preference' },
  { text: 'Agent retrieved 5 relevant memories for context', category: 'agent' },
  { text: 'NVIDIA earnings beat expectations - stock up 8%', category: 'news' },
  { text: 'User asked about AES-256-GCM encryption', category: 'query' },
  { text: 'Session duration: 14 minutes - above average', category: 'system' },
  { text: 'User shared a code snippet for review', category: 'query' },
  { text: 'Agent generated 1536-dim embedding in 3ms', category: 'agent' },
  { text: 'Task: find all memories about user preferences', category: 'agent' },
  { text: 'User mentioned they are a backend engineer', category: 'profile' },
  { text: 'Cosmos IBC volume hits $2B monthly', category: 'news' },
  { text: 'Rate limit reset - resuming normal operations', category: 'system' },
  { text: 'User asked about vector database benchmarks', category: 'query' },
  { text: 'Agent observation: user engagement increasing over time', category: 'agent' },
  { text: 'New user preference: prefers TypeScript over Python', category: 'preference' },
  { text: 'Error: embedding dimension mismatch caught and handled', category: 'system' },
  { text: 'User asked about GraphRAG for knowledge graphs', category: 'query' },
  { text: 'Task completed: weekly memory consolidation', category: 'agent' },
  { text: 'Anchor program verified on Solana Explorer', category: 'system' },
  { text: 'User prefers morning meetings - noted for scheduling', category: 'preference' },
  { text: 'Agent resolved conflict: user moved from SF to NYC', category: 'agent' },
  { text: 'API latency p99: 4.3ms - within SLA', category: 'system' },
  { text: 'User mentioned using Claude for code review', category: 'profile' },
  { text: 'Memory pruning: removed 3 stale entries', category: 'agent' },
  { text: 'Collection encrypted and synced to decentralized storage', category: 'system' },
  { text: 'Session ended - 47 memories written this session', category: 'system' },
];
